### ISSUE TITLE
having to rebuild library every time

### ISSUE THREAD

**Issue by clux** [mockersf/jenkins-api.rs#11]
Hey,

Not sure if this is something on my end, but it's an odd problem I only see with this particular library:

```sh
$ cargo build
   Compiling jenkins_api v0.2.2
   Compiling myapp v0.30.0 (file:///home/clux/repos/myapp)
    Finished dev [unoptimized + debuginfo] target(s) in 11.70 secs
     Running target/debug/deps/myapp-0995c9b5f4b6d1aa
```

essentially every, `cargo build`, `cargo check`, and `cargo test` all have to rebuild this library which adds another sec or two to the iteration cycle (even without any changes to anything). Have you by any chance seen this before?

**Comment by clux** [comment]
Hm, it appears I am behind a bit on versions. Will try to upgrade first.

**Comment by clux** [comment]
Still present on 0.4.0 for me.

**Comment by mockersf** [comment]
Hey, thanks for the report !

I couldn’t reproduce... which version of rust are you using ?

**Comment by clux** [comment]
This is plain stable rust, fresh from rustup. I'm guessing it's some kind of thing related to the dependencies I'm using in combination with jenkins_api then. I can consistently reproduce on a crate that uses:

```toml
[dependencies]
clap = "2.31.2"
error-chain = "0.11.0"
hyper = "0.11.25"
log = "0.4.1"
loggerv = "0.7.1"
openssl-probe = "0.1.2"
regex = "0.2.10"
reqwest = "0.8.5"
serde = "1.0.37"
serde_derive = "1.0.37"
serde_json = "1.0.13"
serde_yaml = "0.7.3"
slack-hook = { git = "https://github.com/clux/rust-slack" }
jenkins_api = "0.2.1"
tera = "0.11.7"
walkdir = "2.1.4"
threadpool = "1.7.1"
chrono = "0.4.1"
semver = { version = "0.9.0", features = ["serde"] }

[dependencies.petgraph]
features = ["serde-1"]
version = "0.4.11"
```

I will try to bisect a bit and see what I can find.
